---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/riordan/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/code/dotfiles
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .gitignore
  - .macos
  - .aliases
  - .exports
  - .vimrc


homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/science
  - osgeo/osgeo4mac

homebrew_installed_packages:
  - adns
  - armadillo
  - arpack
  - autoconf
  - automake
  - bash-completion
  - boost
  - boost-python
  - cfitsio
  - docker-completion
  - docker-compose-completion
  - epsilon
  - freetype
  - freexl
  - gcc
  - gdal
  - gdal2
  - gdbm
  - geos
  - gettext
  - giflib
  - gifsicle
  - git
  - git-lfs
  - gmp
  - gnupg
  - gnutls
  - go
  - gpg-agent
  - hdf5
  - heroku
  - heroku-node
  - htop
  - hub
  - icu4c
  - imagemagick
  - isl
  - jasper
  - jpeg
  - json-c
  - libassuan
  - libdap
  - libevent
  - libffi
  - libgcrypt
  - libgeotiff
  - libgpg-error
  - libkml-dev
  - libksba
  - liblwgeom
  - libmpc
  - libpng
  - libspatialite
  - libtasn1
  - libtiff
  - libtool
  - libunistring
  - libusb
  - libxml2
  - libyaml
  - libyubikey
  - little-cms2
  - mpfr
  - netcdf
  - nettle
  - node
  - npth
  - nvm
  - openjpeg
  - openssl
  - openssl@1.1
  - p11-kit
  - pandoc
  - pcre
  - perl
  - pinentry
  - pinentry-mac
  - popt
  - proj
  - pth
  - python
  - python3
  - readline
  - ruby
  - sqlite
  - superlu
  - szip
  - thefuck
  - tmux
  - unixodbc
  - veclibfort
  - vim
  - webp
  - wget
  - xerces-c
  - xz
  - ykpers
  - you-get
  - zsh
  - zsh-completions

homebrew_cask_apps:
  - 1password
  - alfred
  - atom
  - caffeine
  - colloquy
  - cyberduck
  - docker
  - dropbox
  - eclipse-java
  - evernote
  - firefox
  - flux
  - google-chrome
  - google-drive-file-stream
  - google-earth-pro
  - gpg-suite
  - iterm2
  - java
  - keepingyouawake
  - keybase
  - krita
  - libreoffice
  - little-snitch
  - omnidisksweeper
  - omnifocus
  - omnigraffle
  - omnioutliner
  - satellite-eyes
  - screenflow
  - scrivener
  - sfdx
  - signal
  - sketch
  - skitch
  - slack
  - sonos
  - soqlxplorer
  - spotify
  - tad
  - thunderbird
  - tomighty
  - torbrowser
  - vagrant
  - virtualbox
  - vlc
  - zoomus
  - zotero

pip_install_packages:
    - awscli
